/**
 * Starting catalogue for Warda.
 *
 * Scaffolding, not the deliverable. Names, references, prices and fabrics are
 * plausible for an Algerian womenswear shop in this price band, but the shop
 * supplies the real ones before launch.
 *
 * IMAGE CONVENTION
 * Each product carries an explicit `images` array of real Unsplash photo
 * URLs (`images.unsplash.com/photo-<id>`), sized via the `w=` query param.
 * They are stock photography, not shoots of the actual garments, so treat
 * them as placeholders that get swapped for the shop's own photos before
 * launch — the point is that every link resolves to a real, viewable image
 * instead of a 404 on a path nobody filled in. Images render in a fixed 3:4
 * crop, the fashion standard, so any aspect ratio is safe and portrait shots
 * lose the least.
 *
 * VARIANTS
 * `couleurs` x `tailles` expands into the colour/size matrix, with `stock`
 * giving a per-size count. `rupture` lists the [colour, size] pairs that are
 * sold out, so the seed exercises the out-of-stock UI rather than shipping a
 * catalogue where every size is always available.
 */

const C = {
  noir: { nom: 'Noir', nomAr: 'أسود', hex: '#1E1A1C' },
  creme: { nom: 'Crème', nomAr: 'كريمي', hex: '#EFE6DA' },
  rose: { nom: 'Rose poudré', nomAr: 'وردي باهت', hex: '#E3BFC4' },
  bordeaux: { nom: 'Bordeaux', nomAr: 'عنابي', hex: '#6E2233' },
  bleuNuit: { nom: 'Bleu nuit', nomAr: 'أزرق داكن', hex: '#28324A' },
  sauge: { nom: 'Vert sauge', nomAr: 'أخضر مريمي', hex: '#8C9C82' },
  camel: { nom: 'Camel', nomAr: 'جملي', hex: '#B98A5E' },
  blanc: { nom: 'Blanc', nomAr: 'أبيض', hex: '#F6F3EF' },
  moutarde: { nom: 'Moutarde', nomAr: 'خردلي', hex: '#C9992E' },
  gris: { nom: 'Gris chiné', nomAr: 'رمادي', hex: '#9A9490' },
  terracotta: { nom: 'Terracotta', nomAr: 'طيني', hex: '#B26A4E' },
  lavande: { nom: 'Lavande', nomAr: 'خزامي', hex: '#B7A6C9' },
};

export const CATEGORIES = [
  {
    slug: 'robes',
    nom: { fr: 'Robes', ar: 'فساتين' },
    ordre: 1,
    guideTailles: 'ROBE',
    description: {
      fr: 'Robes longues, midi et courtes. Du quotidien à la soirée.',
      ar: 'فساتين طويلة ومتوسطة وقصيرة. لليوم وللسهرة.',
    },
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80',
  },
  {
    slug: 'tops-et-chemisiers',
    nom: { fr: 'Tops & Chemisiers', ar: 'بلوزات وقمصان' },
    ordre: 2,
    guideTailles: 'HAUT',
    description: {
      fr: 'Blouses, chemisiers et tops, en viscose, coton et satin.',
      ar: 'بلوزات وقمصان وتوبات، من الفيسكوز والقطن والساتان.',
    },
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80',
  },
  {
    slug: 'pantalons-et-jeans',
    nom: { fr: 'Pantalons & Jeans', ar: 'سراويل وجينز' },
    ordre: 3,
    guideTailles: 'BAS',
    description: {
      fr: 'Pantalons fluides, taille haute et jeans, du 34 au 46.',
      ar: 'سراويل انسيابية وعالية الخصر وجينز، من 34 إلى 46.',
    },
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
  },
  {
    slug: 'jupes',
    nom: { fr: 'Jupes', ar: 'تنانير' },
    ordre: 4,
    guideTailles: 'BAS',
    description: {
      fr: 'Jupes midi, longues et plissées.',
      ar: 'تنانير متوسطة وطويلة ومطوية.',
    },
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80',
  },
  {
    slug: 'vestes-et-manteaux',
    nom: { fr: 'Vestes & Manteaux', ar: 'سترات ومعاطف' },
    ordre: 5,
    guideTailles: 'HAUT',
    description: {
      fr: 'Blazers, trenchs et manteaux pour la mi-saison et l’hiver.',
      ar: 'بليزرات ومعاطف لنصف الموسم وللشتاء.',
    },
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
  },
  {
    slug: 'ensembles',
    nom: { fr: 'Ensembles', ar: 'أطقم' },
    ordre: 6,
    guideTailles: 'HAUT',
    description: {
      fr: 'Deux et trois pièces coordonnés, prêts à porter tels quels.',
      ar: 'أطقم من قطعتين وثلاث، جاهزة للارتداء كما هي.',
    },
    image: 'https://images.unsplash.com/photo-1551163943-3f6a855d1153?w=800&q=80',
  },
  {
    slug: 'abayas-et-tenues-modestes',
    nom: { fr: 'Abayas & Tenues modestes', ar: 'عبايات وملابس محتشمة' },
    ordre: 7,
    guideTailles: 'ROBE',
    description: {
      fr: 'Abayas, kimonos et tenues couvrantes, coupées pour tomber droit.',
      ar: 'عبايات وكيمونو وملابس ساترة، مقصوصة لتنسدل بشكل مستقيم.',
    },
    image: 'https://images.unsplash.com/photo-1611328535789-4c1a4e4e5d1c?w=800&q=80',
  },
];

const T_STD = ['S', 'M', 'L', 'XL'];
const T_LARGE = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

export const PRODUITS = [
  // ── Robes ──────────────────────────────────────────────────────────────────
  {
    ref: 'AMIRA',
    nom: { fr: 'Robe longue Amira', ar: 'فستان طويل أميرة' },
    categorie: 'robes',
    prix: 7800,
    ancienPrix: 9200,
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=1000&q=80',
      'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=1000&q=80',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1000&q=80',
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=1000&q=80',
    ],
    description: {
      fr: 'Robe longue en viscose fluide, manches longues et ceinture à nouer. Doublée jusqu’aux genoux.',
      ar: 'فستان طويل من الفيسكوز الانسيابي، بأكمام طويلة وحزام يُربط. مبطّن حتى الركبتين.',
    },
    composition: { fr: '95% viscose, 5% élasthanne', ar: '95% فيسكوز، 5% إيلاستان' },
    entretien: { fr: 'Lavage à 30°C, repassage doux à l’envers', ar: 'غسل على 30 درجة، كي خفيف من الداخل' },
    coupe: 'DROITE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'S',
    mannequinHauteur: 174,
    couleurs: ['noir', 'bordeaux', 'sauge'],
    tailles: T_LARGE,
    stock: 6,
    rupture: [['sauge', 'XS'], ['bordeaux', 'XXL']],
    isFeatured: true,
    isNouveau: true,
  },
  {
    ref: 'NOOR',
    nom: { fr: 'Robe midi Noor', ar: 'فستان متوسط نور' },
    categorie: 'robes',
    prix: 6400,
    images: [
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=1000&q=80',
      'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?w=1000&q=80',
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1000&q=80',
    ],
    description: {
      fr: 'Robe midi en satin mat, col V et jupe évasée. Fermeture par zip invisible au dos.',
      ar: 'فستان متوسط من الساتان المطفي، بياقة V وتنورة واسعة. سحّاب خفي في الظهر.',
    },
    composition: { fr: '100% polyester recyclé', ar: '100% بوليستر معاد تدويره' },
    entretien: { fr: 'Nettoyage à sec recommandé', ar: 'يُنصح بالتنظيف الجاف' },
    coupe: 'AJUSTEE',
    tailleConseil: 'PETIT',
    mannequinTaille: 'M',
    mannequinHauteur: 176,
    couleurs: ['bleuNuit', 'terracotta', 'noir'],
    tailles: T_STD,
    stock: 4,
    rupture: [['terracotta', 'S']],
    isFeatured: true,
  },
  {
    ref: 'YASMINE',
    nom: { fr: 'Robe chemise Yasmine', ar: 'فستان قميص ياسمين' },
    categorie: 'robes',
    prix: 5900,
    images: [
      'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=1000&q=80',
      'https://images.unsplash.com/photo-1550639525-c97d455acf70?w=1000&q=80',
      'https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=1000&q=80',
    ],
    description: {
      fr: 'Robe chemise en coton lavé, boutonnée sur toute la longueur, ceinture amovible.',
      ar: 'فستان قميص من القطن المغسول، بأزرار على كامل الطول، مع حزام قابل للنزع.',
    },
    composition: { fr: '100% coton', ar: '100% قطن' },
    entretien: { fr: 'Lavage à 30°C, séchage à plat', ar: 'غسل على 30 درجة، تجفيف مسطّح' },
    coupe: 'AMPLE',
    tailleConseil: 'GRAND',
    mannequinTaille: 'S',
    mannequinHauteur: 172,
    couleurs: ['creme', 'camel', 'sauge'],
    tailles: T_STD,
    stock: 5,
  },
  {
    ref: 'SELMA',
    nom: { fr: 'Robe plissée Selma', ar: 'فستان مطوي سلمى' },
    categorie: 'robes',
    prix: 8600,
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=1000&q=80',
      'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=1000&q=80',
      'https://images.unsplash.com/photo-1544957992-20514f595d6f?w=1000&q=80',
    ],
    description: {
      fr: 'Robe longue à plissé soleil, taille élastiquée et manches ballon.',
      ar: 'فستان طويل بطيّات شمسية، خصر مطاطي وأكمام منفوخة.',
    },
    composition: { fr: '100% polyester plissé', ar: '100% بوليستر مطوي' },
    entretien: { fr: 'Lavage à la main, ne pas essorer', ar: 'غسل يدوي، دون عصر' },
    coupe: 'AMPLE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'M',
    mannequinHauteur: 175,
    couleurs: ['lavande', 'noir', 'moutarde'],
    tailles: T_STD,
    stock: 3,
    rupture: [['moutarde', 'L'], ['moutarde', 'XL']],
    isNouveau: true,
  },
  {
    ref: 'LEILA',
    nom: { fr: 'Robe droite Leila', ar: 'فستان مستقيم ليلى' },
    categorie: 'robes',
    prix: 4900,
    images: [
      'https://images.unsplash.com/photo-1495385794356-15371f348c31?w=1000&q=80',
      'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1000&q=80',
    ],
    description: {
      fr: 'Robe droite en maille côtelée, sans manches, à porter seule ou sur un col roulé.',
      ar: 'فستان مستقيم من التريكو المضلّع، دون أكمام، يُلبس وحده أو فوق رقبة عالية.',
    },
    composition: { fr: '70% viscose, 30% polyester', ar: '70% فيسكوز، 30% بوليستر' },
    entretien: { fr: 'Lavage à 30°C sur l’envers', ar: 'غسل على 30 درجة من الداخل' },
    coupe: 'DROITE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'S',
    mannequinHauteur: 173,
    couleurs: ['gris', 'noir'],
    tailles: T_STD,
    stock: 7,
  },

  // ── Tops & Chemisiers ──────────────────────────────────────────────────────
  {
    ref: 'INES',
    nom: { fr: 'Blouse Inès', ar: 'بلوزة إيناس' },
    categorie: 'tops-et-chemisiers',
    prix: 3200,
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=1000&q=80',
      'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=1000&q=80',
      'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=1000&q=80',
    ],
    description: {
      fr: 'Blouse en viscose légère, col montant et petits boutons nacrés.',
      ar: 'بلوزة من الفيسكوز الخفيف، بياقة عالية وأزرار صدفية صغيرة.',
    },
    composition: { fr: '100% viscose', ar: '100% فيسكوز' },
    entretien: { fr: 'Lavage à 30°C, repassage doux', ar: 'غسل على 30 درجة، كي خفيف' },
    coupe: 'DROITE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'S',
    mannequinHauteur: 171,
    couleurs: ['blanc', 'rose', 'noir'],
    tailles: T_LARGE,
    stock: 8,
    rupture: [['rose', 'XS']],
    isFeatured: true,
  },
  {
    ref: 'MAYA',
    nom: { fr: 'Chemisier satin Maya', ar: 'قميص ساتان مايا' },
    categorie: 'tops-et-chemisiers',
    prix: 3800,
    images: [
      'https://images.unsplash.com/photo-1551803091-e20673f15770?w=1000&q=80',
      'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=1000&q=80',
    ],
    description: {
      fr: 'Chemisier en satin, coupe droite et poignets boutonnés.',
      ar: 'قميص من الساتان، بقصّة مستقيمة وأساور بأزرار.',
    },
    composition: { fr: '100% polyester satiné', ar: '100% بوليستر ساتان' },
    entretien: { fr: 'Lavage à froid, repassage à basse température', ar: 'غسل بارد، كي على حرارة منخفضة' },
    coupe: 'DROITE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'M',
    mannequinHauteur: 174,
    couleurs: ['creme', 'bleuNuit', 'bordeaux'],
    tailles: T_STD,
    stock: 6,
  },
  {
    ref: 'SAFIA',
    nom: { fr: 'Top col bateau Safia', ar: 'توب بياقة قارب صفية' },
    categorie: 'tops-et-chemisiers',
    prix: 2400,
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=1000&q=80',
      'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=1000&q=80',
    ],
    description: {
      fr: 'Top en maille fine, col bateau et manches trois quarts.',
      ar: 'توب من التريكو الرفيع، بياقة قارب وأكمام ثلاثة أرباع.',
    },
    composition: { fr: '80% viscose, 20% nylon', ar: '80% فيسكوز، 20% نايلون' },
    entretien: { fr: 'Lavage à la main de préférence', ar: 'يُفضّل الغسل اليدوي' },
    coupe: 'AJUSTEE',
    tailleConseil: 'PETIT',
    mannequinTaille: 'S',
    mannequinHauteur: 170,
    couleurs: ['noir', 'creme', 'sauge', 'terracotta'],
    tailles: T_STD,
    stock: 9,
  },
  {
    ref: 'RANIA',
    nom: { fr: 'Chemise oversize Rania', ar: 'قميص فضفاض رانيا' },
    categorie: 'tops-et-chemisiers',
    prix: 3600,
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=1000&q=80',
      'https://images.unsplash.com/photo-1580331451062-99ff652288d7?w=1000&q=80',
      'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=1000&q=80',
    ],
    description: {
      fr: 'Chemise oversize en coton, épaules tombantes, à porter ouverte ou fermée.',
      ar: 'قميص فضفاض من القطن، بأكتاف منسدلة، يُلبس مفتوحا أو مغلقا.',
    },
    composition: { fr: '100% coton popeline', ar: '100% قطن بوبلين' },
    entretien: { fr: 'Lavage à 40°C', ar: 'غسل على 40 درجة' },
    coupe: 'OVERSIZE',
    tailleConseil: 'GRAND',
    mannequinTaille: 'S',
    mannequinHauteur: 175,
    couleurs: ['blanc', 'bleuNuit'],
    tailles: T_STD,
    stock: 5,
    isNouveau: true,
  },

  // ── Pantalons & Jeans ──────────────────────────────────────────────────────
  {
    ref: 'DALIA',
    nom: { fr: 'Pantalon fluide Dalia', ar: 'سروال انسيابي داليا' },
    categorie: 'pantalons-et-jeans',
    prix: 4200,
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=1000&q=80',
      'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=1000&q=80',
      'https://images.unsplash.com/photo-1475178626620-a4d074967452?w=1000&q=80',
    ],
    description: {
      fr: 'Pantalon large taille haute, ceinture élastiquée au dos, deux poches latérales.',
      ar: 'سروال واسع عالي الخصر، بحزام مطاطي في الخلف وجيبين جانبيين.',
    },
    composition: { fr: '65% viscose, 35% polyester', ar: '65% فيسكوز، 35% بوليستر' },
    entretien: { fr: 'Lavage à 30°C', ar: 'غسل على 30 درجة' },
    coupe: 'AMPLE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'M',
    mannequinHauteur: 176,
    couleurs: ['noir', 'camel', 'creme'],
    tailles: T_LARGE,
    stock: 6,
    rupture: [['camel', 'XXL']],
    isFeatured: true,
  },
  {
    ref: 'HIBA',
    nom: { fr: 'Jean droit Hiba', ar: 'جينز مستقيم هبة' },
    categorie: 'pantalons-et-jeans',
    prix: 5200,
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=1000&q=80',
      'https://images.unsplash.com/photo-1475178626620-a4d074967452?w=1000&q=80',
      'https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=1000&q=80',
    ],
    description: {
      fr: 'Jean taille haute coupe droite, denim non extensible, ourlet brut.',
      ar: 'جينز عالي الخصر بقصّة مستقيمة، دنيم غير مطاطي، بحاشية خام.',
    },
    composition: { fr: '100% coton denim', ar: '100% قطن دنيم' },
    entretien: { fr: 'Lavage à l’envers à 30°C', ar: 'غسل مقلوبا على 30 درجة' },
    coupe: 'DROITE',
    tailleConseil: 'PETIT',
    mannequinTaille: 'M',
    mannequinHauteur: 173,
    couleurs: ['bleuNuit', 'noir'],
    tailles: T_STD,
    stock: 5,
  },
  {
    ref: 'MERIEM',
    nom: { fr: 'Pantalon carotte Meriem', ar: 'سروال كاروت مريم' },
    categorie: 'pantalons-et-jeans',
    prix: 3900,
    images: [
      'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=1000&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1000&q=80',
    ],
    description: {
      fr: 'Pantalon carotte à pinces, resserré à la cheville.',
      ar: 'سروال كاروت بثنيات، ضيّق عند الكاحل.',
    },
    composition: { fr: '70% polyester, 28% viscose, 2% élasthanne', ar: '70% بوليستر، 28% فيسكوز، 2% إيلاستان' },
    entretien: { fr: 'Lavage à 30°C', ar: 'غسل على 30 درجة' },
    coupe: 'DROITE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'S',
    mannequinHauteur: 172,
    couleurs: ['gris', 'noir', 'bordeaux'],
    tailles: T_STD,
    stock: 4,
  },

  // ── Jupes ──────────────────────────────────────────────────────────────────
  {
    ref: 'SARAH',
    nom: { fr: 'Jupe midi plissée Sarah', ar: 'تنورة متوسطة مطوية سارة' },
    categorie: 'jupes',
    prix: 3800,
    images: [
      'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=1000&q=80',
      'https://images.unsplash.com/photo-1577900232427-18219b9166a0?w=1000&q=80',
      'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=1000&q=80',
    ],
    description: {
      fr: 'Jupe midi plissée, taille élastiquée, doublée.',
      ar: 'تنورة متوسطة مطوية، بخصر مطاطي ومبطّنة.',
    },
    composition: { fr: '100% polyester', ar: '100% بوليستر' },
    entretien: { fr: 'Lavage à la main, ne pas essorer', ar: 'غسل يدوي، دون عصر' },
    coupe: 'AMPLE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'S',
    mannequinHauteur: 171,
    couleurs: ['sauge', 'noir', 'moutarde'],
    tailles: T_STD,
    stock: 6,
    isNouveau: true,
  },
  {
    ref: 'NADIA',
    nom: { fr: 'Jupe longue Nadia', ar: 'تنورة طويلة نادية' },
    categorie: 'jupes',
    prix: 4100,
    images: [
      'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=1000&q=80',
      'https://images.unsplash.com/photo-1577900232427-18219b9166a0?w=1000&q=80',
    ],
    description: {
      fr: 'Jupe longue coupe droite avec fente au dos, doublée.',
      ar: 'تنورة طويلة بقصّة مستقيمة وفتحة خلفية، مبطّنة.',
    },
    composition: { fr: '62% polyester, 33% viscose, 5% élasthanne', ar: '62% بوليستر، 33% فيسكوز، 5% إيلاستان' },
    entretien: { fr: 'Lavage à 30°C', ar: 'غسل على 30 درجة' },
    coupe: 'DROITE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'M',
    mannequinHauteur: 174,
    couleurs: ['noir', 'camel'],
    tailles: T_STD,
    stock: 5,
  },

  // ── Vestes & Manteaux ──────────────────────────────────────────────────────
  {
    ref: 'LINA',
    nom: { fr: 'Blazer Lina', ar: 'بليزر لينا' },
    categorie: 'vestes-et-manteaux',
    prix: 8900,
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=1000&q=80',
      'https://images.unsplash.com/photo-1548624313-0396c75f8bd8?w=1000&q=80',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=1000&q=80',
    ],
    description: {
      fr: 'Blazer droit à un bouton, doublé, épaules structurées sans être rigides.',
      ar: 'بليزر مستقيم بزر واحد، مبطّن، بأكتاف مهيكلة دون تصلّب.',
    },
    composition: { fr: '63% polyester, 34% viscose, 3% élasthanne', ar: '63% بوليستر، 34% فيسكوز، 3% إيلاستان' },
    entretien: { fr: 'Nettoyage à sec', ar: 'تنظيف جاف' },
    coupe: 'DROITE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'M',
    mannequinHauteur: 175,
    couleurs: ['noir', 'camel', 'bleuNuit'],
    tailles: T_STD,
    stock: 4,
    rupture: [['camel', 'S']],
    isFeatured: true,
  },
  {
    ref: 'ANISSA',
    nom: { fr: 'Trench Anissa', ar: 'ترنش أنيسة' },
    categorie: 'vestes-et-manteaux',
    prix: 12400,
    ancienPrix: 14900,
    images: [
      'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=1000&q=80',
      'https://images.unsplash.com/photo-1520006403909-838d6b92c22e?w=1000&q=80',
      'https://images.unsplash.com/photo-1548624313-0396c75f8bd8?w=1000&q=80',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=1000&q=80',
    ],
    description: {
      fr: 'Trench mi-long croisé, ceinture à nouer et col tailleur.',
      ar: 'ترنش متوسط الطول مزدوج الصدر، بحزام يُربط وياقة كلاسيكية.',
    },
    composition: { fr: '65% coton, 35% polyester', ar: '65% قطن، 35% بوليستر' },
    entretien: { fr: 'Nettoyage à sec', ar: 'تنظيف جاف' },
    coupe: 'AMPLE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'S',
    mannequinHauteur: 176,
    couleurs: ['camel', 'noir'],
    tailles: T_STD,
    stock: 3,
  },
  {
    ref: 'KENZA',
    nom: { fr: 'Gilet long Kenza', ar: 'سترة طويلة كنزة' },
    categorie: 'vestes-et-manteaux',
    prix: 6200,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=1000&q=80',
      'https://images.unsplash.com/photo-1544957992-20514f595d6f?w=1000&q=80',
    ],
    description: {
      fr: 'Gilet long sans manches en maille, ouvert, à porter sur une chemise.',
      ar: 'سترة طويلة دون أكمام من التريكو، مفتوحة، تُلبس فوق قميص.',
    },
    composition: { fr: '50% acrylique, 30% laine, 20% polyester', ar: '50% أكريليك، 30% صوف، 20% بوليستر' },
    entretien: { fr: 'Lavage à la main à froid', ar: 'غسل يدوي بارد' },
    coupe: 'OVERSIZE',
    tailleConseil: 'GRAND',
    mannequinTaille: 'S',
    mannequinHauteur: 172,
    couleurs: ['creme', 'gris'],
    tailles: T_STD,
    stock: 0,
    rupture: [['creme', 'S'], ['creme', 'M'], ['creme', 'L'], ['creme', 'XL'], ['gris', 'S'], ['gris', 'M'], ['gris', 'L'], ['gris', 'XL']],
  },

  // ── Ensembles ──────────────────────────────────────────────────────────────
  {
    ref: 'FARAH',
    nom: { fr: 'Ensemble deux pièces Farah', ar: 'طقم من قطعتين فرح' },
    categorie: 'ensembles',
    prix: 9400,
    images: [
      'https://images.unsplash.com/photo-1551163943-3f6a855d1153?w=1000&q=80',
      'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?w=1000&q=80',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1000&q=80',
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1000&q=80',
    ],
    description: {
      fr: 'Ensemble blouse et pantalon large assortis, en crêpe. Se portent aussi séparément.',
      ar: 'طقم بلوزة وسروال واسع متناسقين، من الكريب. يمكن ارتداؤهما منفصلين.',
    },
    composition: { fr: '100% polyester crêpe', ar: '100% بوليستر كريب' },
    entretien: { fr: 'Lavage à 30°C', ar: 'غسل على 30 درجة' },
    coupe: 'AMPLE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'M',
    mannequinHauteur: 174,
    couleurs: ['sauge', 'noir', 'terracotta'],
    tailles: T_STD,
    stock: 4,
    isFeatured: true,
    isNouveau: true,
  },
  {
    ref: 'SIRINE',
    nom: { fr: 'Ensemble maille Sirine', ar: 'طقم تريكو سيرين' },
    categorie: 'ensembles',
    prix: 7600,
    images: [
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1000&q=80',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=1000&q=80',
      'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?w=1000&q=80',
    ],
    description: {
      fr: 'Top court et jupe longue en maille côtelée, assortis.',
      ar: 'توب قصير وتنورة طويلة من التريكو المضلّع، متناسقان.',
    },
    composition: { fr: '75% viscose, 25% polyester', ar: '75% فيسكوز، 25% بوليستر' },
    entretien: { fr: 'Lavage à la main', ar: 'غسل يدوي' },
    coupe: 'AJUSTEE',
    tailleConseil: 'PETIT',
    mannequinTaille: 'S',
    mannequinHauteur: 173,
    couleurs: ['creme', 'gris', 'rose'],
    tailles: T_STD,
    stock: 5,
  },

  // ── Abayas & Tenues modestes ───────────────────────────────────────────────
  {
    ref: 'RIHAB',
    nom: { fr: 'Abaya Rihab', ar: 'عباية رحاب' },
    categorie: 'abayas-et-tenues-modestes',
    prix: 8200,
    images: [
      'https://images.unsplash.com/photo-1611328535789-4c1a4e4e5d1c?w=1000&q=80',
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=1000&q=80',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1000&q=80',
    ],
    description: {
      fr: 'Abaya droite en crêpe lourd, manches larges et fermeture discrète sur le côté.',
      ar: 'عباية مستقيمة من الكريب الثقيل، بأكمام واسعة وإغلاق خفي من الجانب.',
    },
    composition: { fr: '100% polyester crêpe', ar: '100% بوليستر كريب' },
    entretien: { fr: 'Lavage à 30°C, repassage doux', ar: 'غسل على 30 درجة، كي خفيف' },
    coupe: 'DROITE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'M',
    mannequinHauteur: 178,
    couleurs: ['noir', 'bleuNuit', 'gris'],
    tailles: T_LARGE,
    stock: 7,
    isFeatured: true,
  },
  {
    ref: 'DOUAA',
    nom: { fr: 'Kimono long Douaa', ar: 'كيمونو طويل دعاء' },
    categorie: 'abayas-et-tenues-modestes',
    prix: 5400,
    images: [
      'https://images.unsplash.com/photo-1495385794356-15371f348c31?w=1000&q=80',
      'https://images.unsplash.com/photo-1544957992-20514f595d6f?w=1000&q=80',
    ],
    description: {
      fr: 'Kimono long ouvert en mousseline doublée, à porter sur une tenue simple.',
      ar: 'كيمونو طويل مفتوح من الشيفون المبطّن، يُلبس فوق إطلالة بسيطة.',
    },
    composition: { fr: '100% mousseline polyester', ar: '100% شيفون بوليستر' },
    entretien: { fr: 'Lavage à la main à froid', ar: 'غسل يدوي بارد' },
    coupe: 'AMPLE',
    tailleConseil: 'GRAND',
    mannequinTaille: 'S',
    mannequinHauteur: 174,
    couleurs: ['rose', 'sauge', 'creme'],
    tailles: T_STD,
    stock: 6,
    isNouveau: true,
  },
  {
    ref: 'MALAK',
    nom: { fr: 'Ensemble abaya Malak', ar: 'طقم عباية ملاك' },
    categorie: 'abayas-et-tenues-modestes',
    prix: 11200,
    images: [
      'https://images.unsplash.com/photo-1611328535789-4c1a4e4e5d1c?w=1000&q=80',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=1000&q=80',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1000&q=80',
    ],
    description: {
      fr: 'Abaya et châle assortis, en crêpe satiné, finitions surpiquées.',
      ar: 'عباية وشال متناسقان، من الكريب الساتاني، بخياطة ظاهرة.',
    },
    composition: { fr: '95% polyester, 5% élasthanne', ar: '95% بوليستر، 5% إيلاستان' },
    entretien: { fr: 'Nettoyage à sec recommandé', ar: 'يُنصح بالتنظيف الجاف' },
    coupe: 'DROITE',
    tailleConseil: 'NORMAL',
    mannequinTaille: 'M',
    mannequinHauteur: 177,
    couleurs: ['noir', 'bordeaux'],
    tailles: T_LARGE,
    stock: 3,
    rupture: [['bordeaux', 'XS']],
  },
];

export const COULEURS = C;
export default { CATEGORIES, PRODUITS, COULEURS: C };
